### ISSUE TITLE
error when I use frm npm

### ISSUE THREAD

**Issue by manuelgeek** [ElarianLtd/javascript-sdk#7]
when i do `npm install elarian`
then
`import { Elarian } from 'elarian'`
 i get error
```js
ERROR in ./node_modules/rsocket-tcp-client/build/RSocketTcpClient.js
Module not found: Error: Can't resolve 'net' in '/Users/manuelgeek/VueProjects/Test/raisely/node_modules/rsocket-tcp-client/build'
ERROR in ./node_modules/rsocket-tcp-client/build/RSocketTcpClient.js
Module not found: Error: Can't resolve 'tls' in '/Users/manuelgeek/VueProjects/Test/raisely/node_modules/rsocket-tcp-client/build'
```

I have to install `net`, `tls`, `buffer` separately, even after that i still get 
`_buffer.default.hasOwnProperty is not a function at rsocket-core.v0.0.25.js:371`
    
    
any suggestions ?

tried this within snowpack and nuxt app, 
node 14.16.0

**Comment by aksalj** [comment]
Hello @manuelgeek, try `import { Elarian } from 'elarian/web'` for a browser project.

**Comment by aksalj** [comment]
Hey @manuelgeek,

Can you try something like this - as I see how to better package the web asset:

```js
import elarian from 'elarian/web';
const { Elarian } = elarian;
const client = new Elarian(...);
```

**Comment by manuelgeek** [comment]
@aksalj  getting new error
```js
Uncaught {authToken: Array(1)}authToken: ["Auth token can't be blank"]
```

**Comment by aksalj** [comment]
@manuelgeek Yes, on the browser/mobile, you need to initialize the SDK with an `authToken` instead of `apiKey`. See the docs [here](https://elarianltd.github.io/javascript-sdk/global.html#ClientConfig)
